# .github/workflows/testray-automation-task.yml
name: Run headless Testray script

on:
  schedule:
    # Runs at 6 AM UTC every weekday (Monday–Friday)
    - cron: '0 6 * * 1-5'
  workflow_dispatch:  # Allows manual trigger too

jobs:
  run-testray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # v4 is the latest as of 2025

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # speeds up installs by caching dependencies

      - name: Install dependencies and run script
        working-directory: scripts/testray_automation_tasks
        env:
          TESTRAY_CLIENT_ID: ${{ secrets.TESTRAY_CLIENT_ID }}
          TESTRAY_CLIENT_SECRET: ${{ secrets.TESTRAY_CLIENT_SECRET }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          cd liferay/teams/headless
          python3 headless_testray.py